site_name: DataTorrent Documentation
google_analytics: ['UA-44586211-2', 'docs.datatorrent.com']
site_favicon: favicon.ico
theme: readthedocs
pages:
- DataTorrent RTS: index.md
- Demos:
    - Videos: demo_videos.md
    - Running Apps: demos.md
- Sandbox: sandbox.md
- Development:
    - Creating Applications: create.md
    - Beginner's Guide: beginner.md
    - Tutorials:
        - Top N Words:
            - Introduction: tutorials/topnwords.md
            - Development Environment: tutorials/topnwords-c1.md
            - Building in Java: tutorials/topnwords-c2.md
            - Building with dtAssemble: tutorials/topnwords-c3.md
            - Monitoring with dtManage: tutorials/topnwords-c4.md
            - Visualizing with dtDashboard: tutorials/topnwords-c5.md
            - Advanced Features: tutorials/topnwords-c7.md
            - Appendix: tutorials/topnwords-c6.md
        - Sales Dimensions:
            - Building in Java: tutorials/salesdimensions.md
            - Building with dtAssemble: tutorials/salesdimensions-c2.md
            - Visualizing with dtDashboard: tutorials/salesdimensions-c3.md
            - Monitoring with dtManage: tutorials/salesdimensions-c4.md
    - Apex Development Setup: apex_development_setup.md
    - Generate New Project in IDE: configure_IDE.md
    - Applications: application_development.md
    - Application Packages: application_packages.md
    - Configuration Packages: configuration_packages.md
    - Operators: operator_development.md
    - Library Operators:
        - Kafka Input: operators/kafkaInputOperator.md
        - Dimension Computation: operators/dimensions_computation.md
        - HDHT: operators/hdht.md
        - Deduper: operators/deduper.md
        - File Splitter: operators/file_splitter.md
        - Block Reader: operators/block_reader.md
        - File Output: operators/file_output.md
    - App Data Framework: app_data_framework.md
    - REST API: dtgateway_api.md
- Applications:
    - App Data Tracker: app_data_tracker.md
    - dtIngest: dtingest.md
- Platform:
    - RTS: rts.md
    - dtManage: dtmanage.md
    - dtAssemble: dtassemble.md
    - dtDashboard: dtdashboard.md
    - dtGateway: dtgateway.md
    - Apache Apex: apex.md
    - Apache Apex-Malhar: apex_malhar.md
- Deployment and Operations:
    - Installation: installation.md
    - Configuration: configuration.md
    - Security: dtgateway_security.md
    - Apex CLI: apexcli.md
    - Troubleshooting: troubleshooting.md
- Release Notes: release_notes.md
- Glossary: glossary.md
- Resources: additional_docs.md
